name: agora
description: A new flutter plugin project.
version: 0.1.1
repository: https://github.com/volskaya/agora
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  mobx_codegen: ^2.0.1+3

  loader_coordinator:
    path: /Users/muru/Projects/packages/flutter_helpers/loader_coordinator
  log:
    path: /Users/muru/Projects/packages/flutter_helpers/log
  utils:
    path: /Users/muru/Projects/packages/flutter_helpers/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1

dependency_overrides:
  mobx:
    path: /Users/muru/Projects/forks/mobx.dart/mobx
  mobx_codegen:
    path: /Users/muru/Projects/forks/mobx.dart/mobx_codegen

flutter:
  plugin:
    platforms:
      android:
        package: dev.volskaya.agora
        pluginClass: AgoraPlugin
