name: agora
description: A new flutter plugin project.
version: 0.0.1
author: Roland Volskaya
repository: https://github.com/volskaya/agora

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  freezed: ^0.12.6
  json_annotation:
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+2
  mobx_codegen: ^1.1.0+1

  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  log:
    path: /home/projects/packages/flutter_helpers/log
  utils:
    path: /home/projects/packages/flutter_helpers/utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  freezed_annotation: ^0.12.0
  json_serializable:

dependency_overrides:
  intl: 0.17.0
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  plugin:
    platforms:
      android:
        package: dev.volskaya.agora
        pluginClass: AgoraPlugin

