name: agora
description: A new flutter plugin project.
version: 0.1.1
author: Roland Volskaya
repository: https://github.com/volskaya/agora
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1
  mobx: ^2.0.0-nullsafety.5
  flutter_mobx: ^2.0.0-nullsafety.3
  mobx_codegen: ^2.0.0-nullsafety.2

  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  log:
    path: /home/projects/packages/flutter_helpers/log
  utils:
    path: /home/projects/packages/flutter_helpers/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.0
  json_serializable: ^4.1.0
  freezed: ^0.14.1+1

dependency_overrides:
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

flutter:
  plugin:
    platforms:
      android:
        package: dev.volskaya.agora
        pluginClass: AgoraPlugin

